Implemented Life Journey Code in Benefit Service
DTS-STN/benefit-service pull request #21
Opened 2020-11-26 16:49 UTC by MikeBungay

Implemented the LifeJourney Endpoint to read from a Json and return information on Life Journey's

2020-11-26 17:22 UTC, EricDube requested changes

2020-11-26 17:22 UTC, EricDube commented on handlers/life_journey.go
> +		for i, _ := range ljList {
You should switch this to use the value isntead of i, itll make it easier to read

2020-11-26 17:22 UTC, EricDube commented on main.go
> +// @description This service returns information about lifejourneys
This should say benefits as its for the benefit service, I assume it was a find all replace mistake

2020-11-26 17:22 UTC, EricDube commented on models/LifeJourney.go
> +	Title_fr        string   `json:"title_fr"`
We should try to keep a standard, maybe use TitleFr or TitleFrench to make it easy to read?

2020-11-26 17:22 UTC, EricDube commented on models/LifeJourney.go
> +	Description_fr  string   `json:"description_fr"`
Same as above

2020-11-26 17:22 UTC, EricDube commented on renderings/error.go
> +type QPSError struct {
Change this to BenefitServiceError or something of the like

2020-11-26 17:22 UTC, EricDube commented on server/server.go
> +func setupLifeJourneyFile() {
Not a big deal but adding a space before and after this function will make it easier to read

2020-11-26 19:00 UTC, EricDube requested changes

2020-11-26 19:00 UTC, EricDube commented on models/LifeJourney.go
> +	TitleFr        string         `json:"title_fr"`
You didnt run go fmt here, add a space and save and your IDE should run it

2020-11-30 18:06 UTC, EricDube approved these changes

2020-12-01 17:41 UTC, merged

2020-12-01 17:42 UTC, MikeBungay commented
Merging LifeJourney Code into Dev branch